import { z } from 'zod';

export const entrySchema = z.object({
  id: z.string(),
  dinhDanh: z.string().optional(),

  // Tạo lập
  taolap_Ten: z.string().optional(),
  taolap_DiaChi: z.string().optional(),
  taolap_DaiDien: z.string().optional(),
  taolap_ChucVu: z.string().optional(),
  taolap_SDT: z.string().optional(),
  taolap_Email: z.string().optional(),

  // Cung cấp
  cungcap_Ten: z.string().optional(),
  cungcap_DiaChi: z.string().optional(),
  cungcap_DaiDien: z.string().optional(),
  cungcap_ChucVu: z.string().optional(),
  cungcap_SDT: z.string().optional(),
  cungcap_Email: z.string().optional(),

  // Chung
  loaiDuLieu: z.string().optional(),
  nhanDe: z.string().optional(),
  tomTat: z.string().optional(),
  nguonDuLieu: z.string().optional(),
  ngayPhatHanh: z.string().optional(),
  donViCungCapChiuTrachNhiem: z.string().optional(),
  banQuyen: z.string().optional(),
  chuDe: z.string().optional(),
  donViLienQuan: z.string().optional(),
  duLieuLienQuan: z.string().optional(),
  ngonNgu: z.string().optional(),
  dinhDangDuLieu: z.string().optional(),
  phamViDuLieu: z.string().optional(),
  khaNangCungCap: z.string().optional(),
  thuTucCungCap: z.string().optional(),
  ghiChu: z.string().optional(),
  ngayGiaoNop: z.string().optional(),
  thoiHanBaoQuan: z.string().optional(),

  // Đất đai
  dat_HoTenChu: z.string().optional(),
  dat_SoToBanDo: z.string().optional(),
  dat_SoThua: z.string().optional(),
  dat_LoaiDat: z.string().optional(),
  dat_DienTich: z.string().optional(),
  dat_SoGCN: z.string().optional(),
  dat_SoQuyetDinh: z.string().optional(),
  dat_NgayCap: z.string().optional(),
  loaiHoSo: z.string().optional(),

  // Lưu trữ
  luutru_MaHoSo: z.string().optional(),
  luutru_TieuDe: z.string().optional(),
  luutru_ThoiGianBD: z.string().optional(),
  luutru_ThoiGianKT: z.string().optional(),
  luutru_TuKhoa: z.string().optional(),
  luutru_TongSoTaiLieu: z.string().optional(),
  luutru_SoLuongTo: z.string().optional(),
  luutru_SoLuongTrang: z.string().optional(),
  luutru_TinhTrangVatLy: z.string().optional(),
  luutru_TepTin: z.string().optional(),
  luutru_SoKyHieu: z.string().optional(),
  luutru_HopSo: z.string().optional(),
  luutru_Ke: z.string().optional(),
  luutru_Kho: z.string().optional()
});

export type EntryType = z.infer<typeof entrySchema>;

export const FIELD_LABELS: Record<keyof EntryType, string> = {
  id: "ID",
  dinhDanh: "Định danh",
  taolap_Ten: "Tên CQ/TC (Tạo lập)",
  taolap_DiaChi: "Địa chỉ (Tạo lập)",
  taolap_DaiDien: "Đại diện (Tạo lập)",
  taolap_ChucVu: "Chức vụ (Tạo lập)",
  taolap_SDT: "SĐT (Tạo lập)",
  taolap_Email: "Email (Tạo lập)",

  cungcap_Ten: "Tên CQ/TC (Cung cấp)",
  cungcap_DiaChi: "Địa chỉ (Cung cấp)",
  cungcap_DaiDien: "Đại diện (Cung cấp)",
  cungcap_ChucVu: "Chức vụ (Cung cấp)",
  cungcap_SDT: "SĐT (Cung cấp)",
  cungcap_Email: "Email (Cung cấp)",

  loaiDuLieu: "Loại dữ liệu",
  nhanDe: "Nhan đề",
  tomTat: "Tóm tắt",
  nguonDuLieu: "Nguồn dữ liệu",
  ngayPhatHanh: "Ngày phát hành",
  donViCungCapChiuTrachNhiem: "ĐVCC Chịu trách nhiệm",
  banQuyen: "Bản quyền",
  chuDe: "Chủ đề",
  donViLienQuan: "Đơn vị liên quan",
  duLieuLienQuan: "Dữ liệu liên quan",
  ngonNgu: "Ngôn ngữ",
  dinhDangDuLieu: "Định dạng dữ liệu",
  phamViDuLieu: "Phạm vi dữ liệu",
  khaNangCungCap: "Khả năng cung cấp, sd",
  thuTucCungCap: "Thủ tục cung cấp, sd",
  ghiChu: "Ghi chú",
  ngayGiaoNop: "Ngày giao nộp",
  thoiHanBaoQuan: "Thời hạn bảo quản",

  dat_HoTenChu: "Họ tên chủ SDĐ",
  dat_SoToBanDo: "Số tờ bản đồ",
  dat_SoThua: "Số thửa",
  dat_LoaiDat: "Loại đất",
  dat_DienTich: "Diện tích",
  dat_SoGCN: "Số GCN",
  dat_SoQuyetDinh: "Số quyết định",
  dat_NgayCap: "Ngày cấp",
  loaiHoSo: "Loại hồ sơ đất đai",

  luutru_MaHoSo: "Mã hồ sơ lưu trữ",
  luutru_TieuDe: "Tiêu đề hồ sơ",
  luutru_ThoiGianBD: "Thời gian bắt đầu",
  luutru_ThoiGianKT: "Thời gian kết thúc",
  luutru_TuKhoa: "Từ khóa",
  luutru_TongSoTaiLieu: "Tổng số tài liệu",
  luutru_SoLuongTo: "Số lượng tờ",
  luutru_SoLuongTrang: "Số lượng trang",
  luutru_TinhTrangVatLy: "Tình trạng vật lý",
  luutru_TepTin: "Tệp tin hồ sơ",
  luutru_SoKyHieu: "Số và ký hiệu hồ sơ",
  luutru_HopSo: "Hộp số",
  luutru_Ke: "Kệ",
  luutru_Kho: "Kho lưu trữ",
};
